/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */
/* Copyright (c) 2017 Mobify Research & Development Inc. All rights reserved. */
/* * *  *  * *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  *  * */

/* eslint-disable dot-notation */
/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 17.8
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

/**
* The CustomAttributes model module.
* @module models/CustomAttributes
* @version 17.8
*/
export default class CustomAttributes {
    /**
    * Constructs a new <code>CustomAttributes</code>.
    * Document representing an order address.
    * @alias module:models/CustomAttributes
    * @class
    */
    /**
    * Constructs a <code>CustomAttributes</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {Object} obj Optional instance to populate.
    * @return {Object} The populated <code>CustomAttributes</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || {}
        }

        Object.getOwnPropertyNames(data)
                .filter((prop) => prop.startsWith('c_'))
                .forEach((prop) => {
                    obj[prop] = data[prop]
                })

        return obj
    }
}
